### PR TITLE
Fix issue with saving token to S3

### PR DESCRIPTION
**Pull request by matt-duffy**
This modified line was trying to get the S3 bucket but was not looking
in the correct place in the FilePicker, tested on my server and working 
correctly now.

### CODE REVIEW

**Comment by VTTAssets** [comment]
Can you give me some details on your environment (fvtt version, selfhosted or hosted by a service provider)?

Currently out of town, will eval the pr next week, thanks for your contribution!

**Comment by matt-duffy** [comment]
Sure no problem:

Core Version: 0.8.9

I am self-hosted on an Amazon EC2 instance, all media stored in S3.

Serving through an nginx reverse proxy to the node version of FVTT running on the EC2 instance (ubuntu).

**Comment by matt-duffy** [comment]
And happy to help out, it's a great module!

**Comment by matt-duffy** [comment]
The second commit I just added is a little less straightforward as it is specific to Amazon S3 but if you use S3 to host the tokens and images for actors then at the moment they don't really work in VTTA tokens when using a Chromium browser, due to a CORS caching issue.  So the fix I have added specifically makes things work in a Chromium browser where the images are stored in S3, however I don't think it should have any significant impact on other setups, happy to help test in other situations if needed.

**Comment by matt-duffy** [comment]
Hey there. just wondering if this might get merged or if you need more from me to help move it along?

**Pull request closed without merging**
